name: movies_database
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  dio: ^5.3.0
  flutter:
    sdk: flutter  
  get_it: ^7.6.0
  http: ^0.13.6
  tmdb_api:
  pull_to_refresh: ^2.0.0
  splashscreen:
  flame_splash_screen: ^0.1.0
  another_flutter_splash_screen: ^1.1.4
  transparent_image: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bottom_navy_bar: ^5.6.0
  flutter_launcher_icons: ^0.13.1

  

flutter:
  uses-material-design: true
  assets:
    - assets/placeholder_image.png
    - icons/icon.png

flutter_icons:
  image_path: "icons/icon.png"
  android: true
  ios: true
  
